import AppKit
import AVFoundation
import CryptoKit
import Foundation
import UniformTypeIdentifiers

enum ClipboardLimits {
    static let maximumItemCount = 300
    static let maximumStoredFileSize: Int64 = 1024 * 1024 * 1024
}

enum ClipboardPasteboardPrivacy {
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static func shouldIgnore(_ pasteboard: NSPasteboard) -> Bool {
        let types = pasteboard.types ?? []
        return types.contains(concealedType)
            || types.contains(transientType)
            || types.contains(autoGeneratedType)
    }
}

enum ClipboardOrdering {
    static func newestFirst(_ items: [ClipboardItem]) -> [ClipboardItem] {
        items.sorted { $0.createdAt > $1.createdAt }
    }
}

enum ClipboardKind: String, Codable, CaseIterable, Sendable {
    case text
    case image
    case file
    case video

    var title: String {
        switch self {
        case .text: "文本"
        case .image: "图片"
        case .file: "文件"
        case .video: "视频"
        }
    }

    var icon: String {
        switch self {
        case .text: "doc.text"
        case .image: "photo"
        case .file: "doc"
        case .video: "video"
        }
    }
}

enum ClipboardSensitivity: Equatable {
    case apiToken
    case authentication
    case jsonWebToken
    case privateKey

    var title: String {
        switch self {
        case .apiToken: "疑似 API Token"
        case .authentication: "疑似认证信息"
        case .jsonWebToken: "疑似 JWT"
        case .privateKey: "疑似私钥"
        }
    }
}

struct ClipboardSensitivePresentation: Equatable {
    let sensitivity: ClipboardSensitivity?
    let displayText: String
    let accessibilityText: String
    let isRevealed: Bool

    var requiresReveal: Bool {
        sensitivity != nil && !isRevealed
    }
}

enum SensitiveContentDetector {
    private static let privateKeyPattern = #"-----BEGIN [A-Z ]*PRIVATE KEY-----"#
    private static let jwtPattern = #"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b"#
    private static let providerTokenPattern = #"\b(?:sk|pk|ghp|github_pat|xoxb|xoxp|AKIA)[A-Za-z0-9_\-]{16,}\b"#
    private static let credentialAssignmentPattern = #"(?i)\b(?:api[_-]?key|access[_-]?token|auth(?:orization)?|bearer|secret|password|passwd|cookie|private[_-]?key)\s*[:=]\s*[\"']?[^\s\"']{8,}"#

    static func detect(_ text: String) -> ClipboardSensitivity? {
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        if matches(privateKeyPattern, in: text) {
            return .privateKey
        }
        if matches(jwtPattern, in: text) {
            return .jsonWebToken
        }
        if matches(credentialAssignmentPattern, in: text) {
            return .authentication
        }
        if matches(providerTokenPattern, in: text) || containsHighConfidenceOpaqueSecret(in: text) {
            return .apiToken
        }
        return nil
    }

    static func presentation(
        for text: String,
        revealed: Bool = false
    ) -> ClipboardSensitivePresentation {
        let sensitivity = detect(text)
        guard let sensitivity, !revealed else {
            return ClipboardSensitivePresentation(
                sensitivity: sensitivity,
                displayText: text,
                accessibilityText: sensitivity.map { "\($0.title)，已临时显示" } ?? text,
                isRevealed: revealed
            )
        }

        return ClipboardSensitivePresentation(
            sensitivity: sensitivity,
            displayText: "已隐藏 · \(sensitivity.title)",
            accessibilityText: "\(sensitivity.title)，点击显示一次",
            isRevealed: false
        )
    }

    private static func matches(_ pattern: String, in text: String) -> Bool {
        text.range(of: pattern, options: .regularExpression) != nil
    }

    private static func containsHighConfidenceOpaqueSecret(in text: String) -> Bool {
        text.split(whereSeparator: { $0.isWhitespace }).contains { component in
            let value = String(component)
            guard value.count >= 32, value.count <= 256 else { return false }
            let hasUppercase = value.rangeOfCharacter(from: .uppercaseLetters) != nil
            let hasLowercase = value.rangeOfCharacter(from: .lowercaseLetters) != nil
            let hasNumber = value.rangeOfCharacter(from: .decimalDigits) != nil
            let hasSeparator = value.rangeOfCharacter(from: CharacterSet(charactersIn: "-_+/=")) != nil
            let looksLikeSentence = value.rangeOfCharacter(from: CharacterSet(charactersIn: ".,;:{}[]()<>")) != nil
            return hasUppercase && hasLowercase && hasNumber && hasSeparator && !looksLikeSentence
        }
    }
}

enum JarvisHistoryDateFormatting {
    /// 历史卡片每次重绘都要格式化时间戳，`DateFormatter` 的构造不必每张卡来一次。
    /// 配置完成后只读，`DateFormatter` 在 macOS 10.9 之后对格式化是线程安全的。
    private static let formatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.calendar = Calendar(identifier: .gregorian)
        formatter.dateFormat = "yyyy/MM/dd HH:mm"
        return formatter
    }()

    static func string(from date: Date) -> String {
        formatter.string(from: date)
    }
}

struct ClipboardItem: Codable, Identifiable, Equatable, Sendable {
    let id: UUID
    let createdAt: Date
    let kind: ClipboardKind
    let text: String?
    var textPath: String?
    var imagePath: String?
    var filePath: String?
    var thumbnailPath: String?
    let fileName: String?
    let fileSize: Int64?
    let fileUTI: String?
    let fingerprintValue: String?
    var isStoredCopy: Bool
    var isPinned: Bool

    init(
        id: UUID = UUID(),
        createdAt: Date = Date(),
        kind: ClipboardKind,
        text: String? = nil,
        textPath: String? = nil,
        imagePath: String? = nil,
        filePath: String? = nil,
        thumbnailPath: String? = nil,
        fileName: String? = nil,
        fileSize: Int64? = nil,
        fileUTI: String? = nil,
        fingerprintValue: String? = nil,
        isStoredCopy: Bool = false,
        isPinned: Bool = false
    ) {
        self.id = id
        self.createdAt = createdAt
        self.kind = kind
        self.text = text
        self.textPath = textPath
        self.imagePath = imagePath
        self.filePath = filePath
        self.thumbnailPath = thumbnailPath
        self.fileName = fileName
        self.fileSize = fileSize
        self.fileUTI = fileUTI
        self.fingerprintValue = fingerprintValue
        self.isStoredCopy = isStoredCopy
        self.isPinned = isPinned
    }

    private enum CodingKeys: String, CodingKey {
        case id, createdAt, kind, text, textPath, imagePath, filePath, thumbnailPath, fileName
        case fileSize, fileUTI, fingerprintValue, isStoredCopy, isPinned
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        createdAt = try container.decode(Date.self, forKey: .createdAt)
        kind = try container.decode(ClipboardKind.self, forKey: .kind)
        text = try container.decodeIfPresent(String.self, forKey: .text)
        textPath = try container.decodeIfPresent(String.self, forKey: .textPath)
        imagePath = try container.decodeIfPresent(String.self, forKey: .imagePath)
        filePath = try container.decodeIfPresent(String.self, forKey: .filePath)
        thumbnailPath = try container.decodeIfPresent(String.self, forKey: .thumbnailPath)
        fileName = try container.decodeIfPresent(String.self, forKey: .fileName)
        fileSize = try container.decodeIfPresent(Int64.self, forKey: .fileSize)
        fileUTI = try container.decodeIfPresent(String.self, forKey: .fileUTI)
        fingerprintValue = try container.decodeIfPresent(String.self, forKey: .fingerprintValue)
        isStoredCopy = try container.decodeIfPresent(Bool.self, forKey: .isStoredCopy)
            ?? (kind == .image && imagePath?.contains(
                "/\(JarvisAppIdentity.dataDirectoryName)/Clipboard/"
            ) == true)
        isPinned = try container.decodeIfPresent(Bool.self, forKey: .isPinned) ?? false
    }

    var fingerprint: String {
        if let fingerprintValue {
            return "\(kind.rawValue):\(fingerprintValue)"
        }
        if let text {
            return "text:\(text)"
        }
        if let imagePath {
            return "image:\(imagePath)"
        }
        if let filePath {
            return "\(kind.rawValue):\(filePath)"
        }
        return id.uuidString
    }

    var cachePaths: [String] {
        [textPath, imagePath, filePath, thumbnailPath].compactMap { $0 }
    }

    var preview: String {
        switch kind {
        case .text:
            text?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false
                ? text ?? "文本"
                : "空文本"
        case .image:
            "图片"
        case .file, .video:
            fileName ?? URL(fileURLWithPath: filePath ?? "").lastPathComponent
        }
    }

    var resolvedText: String? {
        guard kind == .text else { return nil }
        if let text {
            return text
        }
        guard let textPath else { return nil }
        return try? String(contentsOf: URL(fileURLWithPath: textPath), encoding: .utf8)
    }

    var clipboardSensitivity: ClipboardSensitivity? {
        guard let resolvedText else { return nil }
        return SensitiveContentDetector.detect(resolvedText)
    }

    var isSensitive: Bool {
        clipboardSensitivity != nil
    }

    func sensitivePresentation(revealed: Bool = false) -> ClipboardSensitivePresentation? {
        guard let resolvedText else { return nil }
        return SensitiveContentDetector.presentation(for: resolvedText, revealed: revealed)
    }

    var canFullscreenPreview: Bool {
        switch kind {
        case .text:
            resolvedText != nil
        case .image, .video:
            hasLocalContent
        case .file:
            false
        }
    }

    var hasLocalContent: Bool {
        switch kind {
        case .text:
            return text != nil
        case .image:
            guard let imagePath else { return false }
            return FileManager.default.fileExists(atPath: imagePath)
        case .file, .video:
            guard let filePath else { return false }
            return FileManager.default.fileExists(atPath: filePath)
        }
    }

    var shortTimestamp: String {
        JarvisHistoryDateFormatting.string(from: createdAt)
    }
}

/// The timer and pasteboard state are main-thread owned; worker closures only
/// use the thread-safe cache store and immutable snapshots captured below.
final class ClipboardService: @unchecked Sendable {
    private let cacheStore: ClipboardCacheStore
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var onChange: (@MainActor @Sendable (ClipboardItem) -> Void)?
    private var prepareCacheSpace: (@Sendable (Int64) -> Void)?

    init(cacheStore: ClipboardCacheStore = ClipboardCacheStore()) {
        self.cacheStore = cacheStore
    }

    func start(
        onChange: @escaping @MainActor @Sendable (ClipboardItem) -> Void,
        prepareCacheSpace: @escaping @Sendable (Int64) -> Void = { _ in }
    ) {
        self.onChange = onChange
        self.prepareCacheSpace = prepareCacheSpace
        timer?.invalidate()
        JarvisLog.info(
            category: .clipboard,
            event: "service.start",
            fields: ["pollIntervalMilliseconds": "550"]
        )
        let timer = Timer(timeInterval: 0.55, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func markCurrentPasteboardAsHandled() {
        lastChangeCount = NSPasteboard.general.changeCount
        JarvisLog.debug(
            category: .clipboard,
            event: "pasteboard.markHandled"
        )
    }

    deinit {
        timer?.invalidate()
        JarvisLog.info(
            category: .clipboard,
            event: "service.stop"
        )
    }

    private func checkPasteboard() {
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        if ClipboardPasteboardPrivacy.shouldIgnore(pasteboard) {
            lastChangeCount = changeCount
            JarvisLog.debug(
                category: .clipboard,
                event: "capture.ignored",
                result: "privacyMarker"
            )
            return
        }
        let capturedAt = Date()
        let fileURLs = Self.fileURLs(from: pasteboard)
        let text = pasteboard.string(forType: .string)
        let pngData = pasteboard.data(forType: .png)
        let tiffData = pngData == nil ? pasteboard.data(forType: .tiff) : nil
        lastChangeCount = changeCount

        if !fileURLs.isEmpty {
            JarvisLog.notice(
                category: .clipboard,
                event: "capture.detected",
                fields: [
                    "kind": "file",
                    "itemCount": String(fileURLs.count)
                ]
            )
            for (index, url) in fileURLs.enumerated() {
                captureFile(url, createdAt: capturedAt.addingTimeInterval(Double(index) * 0.000001))
            }
            return
        }

        if let text, !text.isEmpty {
            JarvisLog.notice(
                category: .clipboard,
                event: "capture.detected",
                fields: [
                    "kind": "text",
                    "bytes": String(Data(text.utf8).count)
                ]
            )
            let callback = onChange
            let cacheStore = self.cacheStore
            let prepareCacheSpace = self.prepareCacheSpace
            DispatchQueue.global(qos: .utility).async {
                let data = Data(text.utf8)
                prepareCacheSpace?(Int64(data.count))
                let path = cacheStore.storeData(data, fileExtension: "txt")
                let item = ClipboardItem(
                    createdAt: capturedAt,
                    kind: .text,
                    text: text,
                    textPath: path,
                    fileSize: Int64(data.count),
                    fingerprintValue: SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined(),
                    isStoredCopy: path != nil
                )
                JarvisLog.info(
                    category: .clipboard,
                    event: "capture.complete",
                    result: path == nil ? "inlineOnly" : "stored",
                    fields: [
                        "kind": "text",
                        "bytes": String(data.count),
                        "storedCopy": String(path != nil)
                    ]
                )
                Task { @MainActor in
                    callback?(item)
                }
            }
            return
        }

        if let pngData {
            JarvisLog.notice(
                category: .clipboard,
                event: "capture.detected",
                fields: [
                    "kind": "image",
                    "bytes": String(pngData.count)
                ]
            )
            captureImage(pngData, createdAt: capturedAt)
            return
        }
        if let tiffData {
            JarvisLog.notice(
                category: .clipboard,
                event: "capture.detected",
                fields: [
                    "kind": "image",
                    "sourceFormat": "tiff",
                    "bytes": String(tiffData.count)
                ]
            )
            DispatchQueue.global(qos: .utility).async { [weak self] in
                guard let imageData = Self.pngData(fromTIFF: tiffData) else {
                    JarvisLog.error(
                        category: .clipboard,
                        event: "capture.convert.failed",
                        fields: ["sourceFormat": "tiff"]
                    )
                    return
                }
                Task { @MainActor [weak self] in
                    self?.captureImage(imageData, createdAt: capturedAt)
                }
            }
        }
    }

    static func fileURLs(from pasteboard: NSPasteboard) -> [URL] {
        pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        )?.compactMap { $0 as? URL }
            .filter(\.isFileURL) ?? []
    }

    private static func pngData(fromTIFF tiffData: Data) -> Data? {
        guard let bitmap = NSBitmapImageRep(data: tiffData) else { return nil }
        return bitmap.representation(using: .png, properties: [:])
    }

    private func captureFile(_ url: URL, createdAt: Date) {
        let callback = onChange
        let cacheStore = self.cacheStore
        let prepareCacheSpace = self.prepareCacheSpace
        DispatchQueue.global(qos: .utility).async {
            guard let values = try? url.resourceValues(forKeys: [.fileSizeKey, .contentTypeKey, .contentModificationDateKey])
            else {
                JarvisLog.error(
                    category: .clipboard,
                    event: "capture.fileMetadata.failed",
                    fields: ["kind": "file"]
                )
                return
            }

            let fileSize = Int64(values.fileSize ?? 0)
            let contentType = values.contentType
            let modificationTimestamp = values.contentModificationDate?.timeIntervalSince1970 ?? 0
            let kind = Self.kind(for: url, contentType: contentType)
            let storedPath: String?
            if fileSize <= ClipboardLimits.maximumStoredFileSize {
                prepareCacheSpace?(fileSize)
                storedPath = cacheStore.storeFile(url, fileSize: fileSize)
            } else {
                storedPath = nil
            }
            let path = storedPath ?? url.path
            let finishCapture: @Sendable (String?) -> Void = { thumbnailPath in
                let fingerprint = "\(url.path)|\(fileSize)|\(modificationTimestamp)"
                let item = ClipboardItem(
                    createdAt: createdAt,
                    kind: kind,
                    filePath: path,
                    thumbnailPath: thumbnailPath,
                    fileName: url.lastPathComponent,
                    fileSize: fileSize,
                    fileUTI: contentType?.identifier,
                    fingerprintValue: fingerprint,
                    isStoredCopy: storedPath != nil
                )
                JarvisLog.info(
                    category: .clipboard,
                    event: "capture.complete",
                    result: storedPath == nil ? "sourceReference" : "stored",
                    fields: [
                        "kind": kind.rawValue,
                        "bytes": String(fileSize),
                        "storedCopy": String(storedPath != nil),
                        "thumbnailStored": String(thumbnailPath != nil)
                    ]
                )
                Task { @MainActor in
                    callback?(item)
                }
            }

            guard kind == .video else {
                finishCapture(nil)
                return
            }

            let cacheStore = self.cacheStore
            let prepareCacheSpace = self.prepareCacheSpace
            ClipboardVideoThumbnailGenerator.makeCGImageAsync(for: URL(fileURLWithPath: path)) { image in
                guard let image,
                      let data = NSBitmapImageRep(cgImage: image).representation(using: .png, properties: [:])
                else {
                    JarvisLog.debug(
                        category: .clipboard,
                        event: "capture.videoThumbnail.unavailable"
                    )
                    finishCapture(nil)
                    return
                }
                DispatchQueue.global(qos: .utility).async {
                    prepareCacheSpace?(Int64(data.count))
                    finishCapture(cacheStore.storeData(data, fileExtension: "png"))
                }
            }
        }
    }

    private func captureImage(_ data: Data, createdAt: Date) {
        let callback = onChange
        let cacheStore = self.cacheStore
        let prepareCacheSpace = self.prepareCacheSpace
        DispatchQueue.global(qos: .utility).async {
            prepareCacheSpace?(Int64(data.count))
            let path = cacheStore.storeData(data, fileExtension: "png")
            let item = ClipboardItem(
                createdAt: createdAt,
                kind: .image,
                imagePath: path,
                // 图片项不留名字：拖出去时按「复制时间」现取（`ClipboardSharing`）。
                // 存一个固定的 `图片.png` 只会让每次拖拽都撞名。
                fileName: nil,
                fileSize: Int64(data.count),
                fileUTI: UTType.png.identifier,
                fingerprintValue: SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined(),
                isStoredCopy: path != nil
            )
            JarvisLog.info(
                category: .clipboard,
                event: "capture.complete",
                result: path == nil ? "unavailable" : "stored",
                fields: [
                    "kind": "image",
                    "bytes": String(data.count),
                    "storedCopy": String(path != nil)
                ]
            )
            Task { @MainActor in
                callback?(item)
            }
        }
    }

    private static func kind(for url: URL, contentType: UTType?) -> ClipboardKind {
        if contentType?.conforms(to: .movie) == true {
            return .video
        }
        let videoExtensions = Set(["mp4", "mov", "m4v", "avi", "mkv", "webm", "wmv", "flv"])
        return videoExtensions.contains(url.pathExtension.lowercased()) ? .video : .file
    }

    private func storeFile(_ sourceURL: URL, fileSize: Int64) -> String? {
        // Keep very large files as references so copying a movie never blocks
        // the app or silently fills the user's disk.
        guard fileSize <= ClipboardLimits.maximumStoredFileSize else { return nil }
        prepareCacheSpace?(fileSize)
        return cacheStore.storeFile(sourceURL, fileSize: fileSize)
    }
}

final class ClipboardStore: @unchecked Sendable {
    private let file: JarvisJSONFile<[ClipboardItem]>

    init() {
        file = JarvisJSONFile(
            directoryURL: JarvisAppDirectory.url(),
            fileName: "clipboard-history.json",
            logDomain: "history",
            logCategory: .clipboard
        )
    }

    init(directoryURL: URL) {
        file = JarvisJSONFile(
            directoryURL: directoryURL,
            fileName: "clipboard-history.json",
            logDomain: "history",
            logCategory: .clipboard
        )
    }

    func load() -> [ClipboardItem] {
        ClipboardOrdering.newestFirst(file.readOrDefault([]))
    }

    /// - Parameter revision: 调用方读取待写入状态时分配的版本号。早于已落盘版本的
    ///   写入会被丢弃，`nil` 表示无条件写入。
    @discardableResult
    func save(_ items: [ClipboardItem], revision: UInt64? = nil) -> Bool {
        file.write(items, revision: revision)
    }
}
