import Foundation
import ImageIO
import Vision

enum ScreenshotTranslationLanguage: String, CaseIterable, Codable, Identifiable, Sendable {
    case simplifiedChinese = "zh-Hans"
    case traditionalChinese = "zh-Hant"
    case english = "en"
    case japanese = "ja"
    case korean = "ko"

    var id: String {
        rawValue
    }

    var title: String {
        switch self {
        case .simplifiedChinese: "简体中文"
        case .traditionalChinese: "繁體中文"
        case .english: "English"
        case .japanese: "日本語"
        case .korean: "한국어"
        }
    }
}

struct ScreenshotTranslationConfiguration: Equatable, Sendable {
    static let endpointKey = AIAPIConfiguration.endpointKey
    static let modelKey = AIAPIConfiguration.modelKey
    static let targetLanguageKey = "jarvis.screenshot.translation.target-language"
    static let defaultEndpoint = AIAPIConfiguration.defaultEndpoint
    static let defaultModel = AIAPIConfiguration.defaultModel

    let api: AIAPIConfiguration
    var targetLanguage: ScreenshotTranslationLanguage

    var endpoint: String {
        api.endpoint
    }

    var model: String {
        api.model
    }

    var apiKey: String {
        api.apiKey
    }

    var isConfigured: Bool {
        api.isConfigured
    }

    init(
        endpoint: String,
        model: String,
        apiKey: String,
        targetLanguage: ScreenshotTranslationLanguage
    ) {
        api = AIAPIConfiguration(endpoint: endpoint, model: model, apiKey: apiKey)
        self.targetLanguage = targetLanguage
    }

    init(
        api: AIAPIConfiguration,
        targetLanguage: ScreenshotTranslationLanguage
    ) {
        self.api = api
        self.targetLanguage = targetLanguage
    }

    static func load(
        defaults: UserDefaults = .standard,
        keychain: AIAPIKeychain = .shared
    ) -> Self {
        Self(
            api: AIAPIConfiguration.load(defaults: defaults, keychain: keychain),
            targetLanguage: ScreenshotTranslationLanguage(
                rawValue: defaults.string(forKey: targetLanguageKey) ?? ""
            ) ?? .simplifiedChinese
        )
    }
}

struct ScreenshotOCRBlock: Equatable, Identifiable, Sendable {
    let id: UUID
    let text: String
    /// Vision's normalized coordinate space converted to a top-left origin.
    /// x/y/width/height are all in the 0...1 range.
    let normalizedBounds: CGRect
    let confidence: Float
}

struct ScreenshotTranslationBlock: Equatable, Identifiable, Sendable {
    let id: UUID
    let sourceText: String
    var translatedText: String
    /// Bounds remain owned by Vision and are never generated by the model.
    let normalizedBounds: CGRect
    let confidence: Float
}

struct ScreenshotTranslationRenderBlock: Equatable, Identifiable, Sendable {
    let id: UUID
    let sourceText: String
    let translatedText: String
    let bounds: CGRect
    let confidence: Float
}

enum ScreenshotTranslationGeometry {
    static func canvasBounds(for normalizedBounds: CGRect, in canvasRect: CGRect) -> CGRect {
        CGRect(
            x: canvasRect.minX + normalizedBounds.minX * canvasRect.width,
            y: canvasRect.minY + normalizedBounds.minY * canvasRect.height,
            width: normalizedBounds.width * canvasRect.width,
            height: normalizedBounds.height * canvasRect.height
        )
    }
}

enum ScreenshotTranslationState: Equatable {
    case idle
    case recognizing
    case translating(completed: Int, total: Int)
    case completed(count: Int)
    case failed(String)

    var isRunning: Bool {
        switch self {
        case .recognizing, .translating: true
        default: false
        }
    }
}

enum ScreenshotTranslationError: LocalizedError, Equatable {
    case invalidImage
    case noTextFound

    var errorDescription: String? {
        switch self {
        case .invalidImage: "无法读取截图图像"
        case .noTextFound: "没有识别到可翻译的文字"
        }
    }
}

struct ScreenshotTranslationService: Sendable {
    private let apiClient: any AITranslationAPI

    init(apiClient: any AITranslationAPI = OpenAICompatibleAPIClient()) {
        self.apiClient = apiClient
    }

    func recognizeText(in data: Data) async throws -> [ScreenshotOCRBlock] {
        try await withCheckedThrowingContinuation { continuation in
            DispatchQueue.global(qos: .userInitiated).async {
                do {
                    guard let source = CGImageSourceCreateWithData(data as CFData, nil),
                          let image = CGImageSourceCreateImageAtIndex(source, 0, nil)
                    else {
                        throw ScreenshotTranslationError.invalidImage
                    }

                    let request = VNRecognizeTextRequest()
                    request.recognitionLevel = .accurate
                    request.usesLanguageCorrection = true
                    request.minimumTextHeight = 0.008

                    let handler = VNImageRequestHandler(cgImage: image, options: [:])
                    try handler.perform([request])

                    let blocks = (request.results ?? []).compactMap { observation -> ScreenshotOCRBlock? in
                        guard let candidate = observation.topCandidates(1).first else { return nil }
                        let text = candidate.string.trimmingCharacters(in: .whitespacesAndNewlines)
                        guard !text.isEmpty else { return nil }
                        let box = observation.boundingBox
                        let topLeftBounds = CGRect(
                            x: box.minX,
                            y: 1 - box.maxY,
                            width: box.width,
                            height: box.height
                        )
                        return ScreenshotOCRBlock(
                            id: UUID(),
                            text: text,
                            normalizedBounds: topLeftBounds,
                            confidence: candidate.confidence
                        )
                    }

                    guard !blocks.isEmpty else {
                        throw ScreenshotTranslationError.noTextFound
                    }
                    continuation.resume(returning: blocks)
                } catch {
                    continuation.resume(throwing: error)
                }
            }
        }
    }

    func translate(
        _ blocks: [ScreenshotOCRBlock],
        targetLanguage: ScreenshotTranslationLanguage,
        configuration: ScreenshotTranslationConfiguration
    ) async throws -> [ScreenshotTranslationBlock] {
        guard !blocks.isEmpty else { throw ScreenshotTranslationError.noTextFound }
        let inputs = blocks.map { AITranslationInput(id: $0.id.uuidString, text: $0.text) }
        let outputs = try await apiClient.translate(
            inputs,
            targetLanguage: targetLanguage.title,
            configuration: configuration.api
        )
        let translationsByID = outputs.reduce(into: [String: String]()) { result, item in
            result[item.id] = item.translation
        }
        let result = blocks.compactMap { block -> ScreenshotTranslationBlock? in
            guard let translatedText = translationsByID[block.id.uuidString],
                  !translatedText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            else {
                return nil
            }
            return ScreenshotTranslationBlock(
                id: block.id,
                sourceText: block.text,
                translatedText: translatedText,
                normalizedBounds: block.normalizedBounds,
                confidence: block.confidence
            )
        }
        guard result.count == blocks.count else {
            throw AIAPIError.incompleteTranslation(expected: blocks.count, actual: result.count)
        }
        return result
    }
}
