import Foundation
import ImageIO
import NaturalLanguage
import Vision

enum ScreenshotTranslationLanguage: String, CaseIterable, Codable, Identifiable, Sendable {
    case simplifiedChinese = "zh-Hans"
    case traditionalChinese = "zh-Hant"
    case english = "en"
    case japanese = "ja"
    case korean = "ko"
    case spanish = "es"

    var id: String {
        rawValue
    }

    var title: String {
        switch self {
        case .simplifiedChinese: "简体中文"
        case .traditionalChinese: "繁體中文"
        case .english: "English"
        case .japanese: "日本語"
        case .korean: "한국어"
        case .spanish: "Español"
        }
    }

    var appleLanguageIdentifier: String {
        switch self {
        case .simplifiedChinese: "zh-Hans"
        case .traditionalChinese: "zh-Hant"
        case .english: "en-US"
        case .japanese: "ja-JP"
        case .korean: "ko-KR"
        case .spanish: "es-ES"
        }
    }

    var localeLanguage: Locale.Language {
        Locale.Language(identifier: appleLanguageIdentifier)
    }

    func matches(_ language: Locale.Language) -> Bool {
        let code = language.languageCode?.identifier.lowercased()
        let script = language.script?.identifier
        switch self {
        case .simplifiedChinese:
            return code == "zh" && (script == nil || script == "Hans")
        case .traditionalChinese:
            return code == "zh" && script == "Hant"
        case .english:
            return code == "en"
        case .japanese:
            return code == "ja"
        case .korean:
            return code == "ko"
        case .spanish:
            return code == "es"
        }
    }
}

enum ScreenshotTranslationConfiguration {
    static let targetLanguageKey = "jarvis.screenshot.translation.target-language"

    static func loadTargetLanguage(
        defaults: UserDefaults = .standard
    ) -> ScreenshotTranslationLanguage {
        ScreenshotTranslationLanguage(
            rawValue: defaults.string(forKey: targetLanguageKey) ?? ""
        ) ?? .simplifiedChinese
    }
}

struct ScreenshotOCRBlock: Equatable, Identifiable, Sendable {
    let id: UUID
    let text: String
    /// Vision's normalized coordinate space converted to a top-left origin.
    /// x/y/width/height are all in the 0...1 range.
    let normalizedBounds: CGRect
    let confidence: Float
    let lineHeight: CGFloat
    let sourceLines: [ScreenshotTranslationLine]

    init(
        id: UUID,
        text: String,
        normalizedBounds: CGRect,
        confidence: Float,
        lineHeight: CGFloat? = nil,
        sourceLines: [ScreenshotTranslationLine] = []
    ) {
        self.id = id
        self.text = text
        self.normalizedBounds = normalizedBounds
        self.confidence = confidence
        self.lineHeight = max(0.001, lineHeight ?? normalizedBounds.height)
        self.sourceLines = sourceLines.isEmpty
            ? [ScreenshotTranslationLine(
                text: text,
                bounds: normalizedBounds,
                lineHeight: lineHeight ?? normalizedBounds.height
            )]
            : sourceLines
    }
}

struct ScreenshotTranslationBlock: Equatable, Identifiable, Sendable {
    let id: UUID
    let sourceText: String
    var translatedText: String
    /// Bounds remain owned by Vision and are never generated by the model.
    let normalizedBounds: CGRect
    let confidence: Float
    let lineHeight: CGFloat
    let sourceLines: [ScreenshotTranslationLine]

    init(
        id: UUID,
        sourceText: String,
        translatedText: String,
        normalizedBounds: CGRect,
        confidence: Float,
        lineHeight: CGFloat? = nil,
        sourceLines: [ScreenshotTranslationLine] = []
    ) {
        self.id = id
        self.sourceText = sourceText
        self.translatedText = translatedText
        self.normalizedBounds = normalizedBounds
        self.confidence = confidence
        self.lineHeight = max(0.001, lineHeight ?? normalizedBounds.height)
        self.sourceLines = sourceLines.isEmpty
            ? [ScreenshotTranslationLine(
                text: sourceText,
                bounds: normalizedBounds,
                lineHeight: lineHeight ?? normalizedBounds.height
            )]
            : sourceLines
    }
}

struct ScreenshotTranslationRenderBlock: Equatable, Identifiable, Sendable {
    let id: UUID
    let sourceText: String
    let translatedText: String
    let bounds: CGRect
    let confidence: Float
    let sourceLineHeight: CGFloat
    let fontSize: CGFloat
    let lineLimit: Int
    let horizontalPadding: CGFloat
    let sourceLines: [ScreenshotTranslationLine]
    let displayLines: [String]
    let displayLineBounds: [CGRect]

    init(
        id: UUID,
        sourceText: String,
        translatedText: String,
        bounds: CGRect,
        confidence: Float,
        sourceLineHeight: CGFloat = 0,
        fontSize: CGFloat = 0,
        lineLimit: Int = 1,
        horizontalPadding: CGFloat = 6,
        sourceLines: [ScreenshotTranslationLine] = [],
        displayLines: [String] = [],
        displayLineBounds: [CGRect] = []
    ) {
        self.id = id
        self.sourceText = sourceText
        self.translatedText = translatedText
        self.bounds = bounds
        self.confidence = confidence
        self.sourceLineHeight = sourceLineHeight
        self.fontSize = fontSize
        self.lineLimit = lineLimit
        self.horizontalPadding = horizontalPadding
        self.sourceLines = sourceLines
        self.displayLines = displayLines
        self.displayLineBounds = displayLineBounds
    }
}

struct ScreenshotTranslationLanguageGroup: Equatable, Sendable {
    let source: Locale.Language?
    let blocks: [ScreenshotOCRBlock]
}

struct ScreenshotTranslationPlan: Equatable, Sendable {
    let groups: [ScreenshotTranslationLanguageGroup]

    var translatableCount: Int {
        groups.reduce(0) { $0 + $1.blocks.count }
    }
}

private struct ScreenshotOCRCharacter {
    let range: Range<String.Index>
    let normalizedBounds: CGRect
}

private final class ScreenshotOCRRequestBox: @unchecked Sendable {
    private let lock = NSLock()
    private var request: VNRecognizeTextRequest?
    private var cancelled = false

    var isCancelled: Bool {
        lock.lock()
        defer { lock.unlock() }
        return cancelled
    }

    func setRequest(_ request: VNRecognizeTextRequest) {
        lock.lock()
        self.request = request
        let shouldCancel = cancelled
        lock.unlock()
        if shouldCancel {
            request.cancel()
        }
    }

    func cancel() {
        lock.lock()
        cancelled = true
        let request = self.request
        lock.unlock()
        request?.cancel()
    }
}

enum ScreenshotTranslationGeometry {
    static func canvasBounds(for normalizedBounds: CGRect, in canvasRect: CGRect) -> CGRect {
        CGRect(
            x: canvasRect.minX + normalizedBounds.minX * canvasRect.width,
            y: canvasRect.minY + normalizedBounds.minY * canvasRect.height,
            width: normalizedBounds.width * canvasRect.width,
            height: normalizedBounds.height * canvasRect.height
        )
    }
}

enum ScreenshotTranslationError: LocalizedError, Equatable {
    case invalidImage
    case noTextFound
    case unsupportedLanguagePair

    var errorDescription: String? {
        switch self {
        case .invalidImage: "无法读取截图图像"
        case .noTextFound: "没有识别到可翻译的文字"
        case .unsupportedLanguagePair: "系统翻译不支持该语言，请先在设置中下载对应语言包"
        }
    }
}

struct ScreenshotTranslationService: Sendable {
    func recognizeText(in data: Data) async throws -> [ScreenshotOCRBlock] {
        let requestBox = ScreenshotOCRRequestBox()
        return try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                DispatchQueue.global(qos: .userInitiated).async {
                    do {
                        guard !requestBox.isCancelled else {
                            throw CancellationError()
                        }
                        guard let image = Self.ocrImage(from: data) else {
                            throw ScreenshotTranslationError.invalidImage
                        }

                        let request = VNRecognizeTextRequest()
                        request.recognitionLevel = .accurate
                        request.usesLanguageCorrection = true
                        request.automaticallyDetectsLanguage = true
                        requestBox.setRequest(request)

                        let handler = VNImageRequestHandler(cgImage: image, options: [:])
                        try handler.perform([request])
                        guard !requestBox.isCancelled else {
                            throw CancellationError()
                        }

                        let blocks = (request.results ?? []).flatMap { observation -> [ScreenshotOCRBlock] in
                            guard let candidate = observation.topCandidates(1).first else { return [] }
                            guard !candidate.string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
                                return []
                            }
                            let box = observation.boundingBox
                            let topLeftBounds = CGRect(
                                x: box.minX,
                                y: 1 - box.maxY,
                                width: box.width,
                                height: box.height
                            )
                            return Self.visualTextBlocks(
                                from: candidate,
                                fallbackBounds: topLeftBounds,
                                confidence: candidate.confidence
                            )
                        }

                        let lineBlocks = Self.mergedLineBlocks(from: blocks)
                        let merged = Self.mergedParagraphBlocks(from: lineBlocks)
                        guard !merged.isEmpty else {
                            throw ScreenshotTranslationError.noTextFound
                        }
                        continuation.resume(returning: merged)
                    } catch {
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            requestBox.cancel()
        }
    }

    static func classify(
        _ blocks: [ScreenshotOCRBlock],
        targetLanguage: ScreenshotTranslationLanguage
    ) -> ScreenshotTranslationPlan {
        var grouped: [String: (source: Locale.Language?, blocks: [ScreenshotOCRBlock])] = [:]
        let recognizer = makeLanguageRecognizer()
        for block in blocks {
            guard needsTranslation(block.text) else { continue }
            let language = detectedLanguage(for: block.text, using: recognizer)
            if let language, targetLanguage.matches(language) {
                continue
            }
            let key = languageKey(for: language)
            if grouped[key] == nil {
                grouped[key] = (language, [])
            }
            grouped[key]?.blocks.append(block)
        }

        let groups = grouped.values
            .map { ScreenshotTranslationLanguageGroup(source: $0.source, blocks: $0.blocks) }
            .sorted { lhs, rhs in
                if lhs.blocks.count != rhs.blocks.count {
                    return lhs.blocks.count > rhs.blocks.count
                }
                return languageKey(for: lhs.source) < languageKey(for: rhs.source)
            }
        return ScreenshotTranslationPlan(groups: groups)
    }

    static func needsTranslation(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return false }
        return trimmed.contains { character in
            character.isLetter
        }
    }

    /// 复用同一个识别器。`NLLanguageRecognizer` 的构造要加载模型，逐块新建的话
    /// 一张 200 块的截图就是 200 次初始化。
    static func makeLanguageRecognizer() -> NLLanguageRecognizer {
        let recognizer = NLLanguageRecognizer()
        recognizer.languageConstraints = [
            .simplifiedChinese,
            .traditionalChinese,
            .english,
            .japanese,
            .korean,
            .spanish
        ]
        return recognizer
    }

    static func detectedLanguage(
        for text: String,
        using recognizer: NLLanguageRecognizer
    ) -> Locale.Language? {
        recognizer.processString(text)
        let hypotheses = recognizer.languageHypotheses(withMaximum: 5)
        guard let best = hypotheses.max(by: { $0.value < $1.value }),
              best.value >= 0.45
        else {
            return nil
        }
        return ScreenshotAppleTranslation.normalizedLanguage(
            Locale.Language(identifier: best.key.rawValue)
        )
    }

    static func mergedLineBlocks(from blocks: [ScreenshotOCRBlock]) -> [ScreenshotOCRBlock] {
        let sorted = blocks.sorted { lhs, rhs in
            let yDelta = lhs.normalizedBounds.midY - rhs.normalizedBounds.midY
            if abs(yDelta) > 0.012 {
                return lhs.normalizedBounds.minY < rhs.normalizedBounds.minY
            }
            return lhs.normalizedBounds.minX < rhs.normalizedBounds.minX
        }

        var merged: [ScreenshotOCRBlock] = []
        for block in sorted {
            guard let last = merged.last else {
                merged.append(block)
                continue
            }

            let verticalTolerance = max(0.012, max(last.normalizedBounds.height, block.normalizedBounds.height) * 0.55)
            let sameLine = abs(last.normalizedBounds.midY - block.normalizedBounds.midY) <= verticalTolerance
            let gap = block.normalizedBounds.minX - last.normalizedBounds.maxX
            let lineHeight = max(last.normalizedBounds.height, block.normalizedBounds.height)
            let close = gap <= visualRunGapThreshold(for: lineHeight)
            if sameLine, close, gap > -0.02 {
                let mergedBounds = last.normalizedBounds.union(block.normalizedBounds)
                merged[merged.count - 1] = ScreenshotOCRBlock(
                    id: last.id,
                    text: joinedText(last.text, block.text),
                    normalizedBounds: mergedBounds,
                    confidence: min(last.confidence, block.confidence),
                    lineHeight: max(last.lineHeight, block.lineHeight),
                    sourceLines: [ScreenshotTranslationLine(
                        text: joinedText(last.text, block.text),
                        bounds: mergedBounds,
                        lineHeight: max(last.lineHeight, block.lineHeight)
                    )]
                )
            } else {
                merged.append(block)
            }
        }
        return merged
    }

    private static func visualTextBlocks(
        from candidate: VNRecognizedText,
        fallbackBounds: CGRect,
        confidence: Float
    ) -> [ScreenshotOCRBlock] {
        let text = candidate.string
        guard !text.isEmpty,
              let characters = characterBoxes(for: candidate),
              !characters.isEmpty
        else {
            return [ScreenshotOCRBlock(
                id: UUID(),
                text: text.trimmingCharacters(in: .whitespacesAndNewlines),
                normalizedBounds: fallbackBounds,
                confidence: confidence
            )]
        }

        var blocks: [ScreenshotOCRBlock] = []
        var runStart = characters[0].range.lowerBound
        var runEnd = characters[0].range.upperBound
        var runBounds = characters[0].normalizedBounds

        for character in characters.dropFirst() {
            let gap = character.normalizedBounds.minX - runBounds.maxX
            let lineHeight = max(runBounds.height, character.normalizedBounds.height)
            let separatesVisualRuns = gap > visualRunGapThreshold(for: lineHeight)

            if separatesVisualRuns {
                appendVisualTextBlock(
                    from: text,
                    range: runStart ..< runEnd,
                    bounds: runBounds,
                    confidence: confidence,
                    to: &blocks
                )
                runStart = character.range.lowerBound
                runEnd = character.range.upperBound
                runBounds = character.normalizedBounds
            } else {
                runEnd = character.range.upperBound
                runBounds = runBounds.union(character.normalizedBounds)
            }
        }

        appendVisualTextBlock(
            from: text,
            range: runStart ..< runEnd,
            bounds: runBounds,
            confidence: confidence,
            to: &blocks
        )
        return blocks.isEmpty ? [ScreenshotOCRBlock(
            id: UUID(),
            text: text.trimmingCharacters(in: .whitespacesAndNewlines),
            normalizedBounds: fallbackBounds,
            confidence: confidence
        )] : blocks
    }

    private static func visualRunGapThreshold(for lineHeight: CGFloat) -> CGFloat {
        max(0.004, min(0.018, lineHeight * 0.65))
    }

    private static func characterBoxes(for candidate: VNRecognizedText) -> [ScreenshotOCRCharacter]? {
        let text = candidate.string
        var characters: [ScreenshotOCRCharacter] = []
        var failed = false

        text.enumerateSubstrings(
            in: text.startIndex ..< text.endIndex,
            options: .byComposedCharacterSequences
        ) { _, range, _, _ in
            let character = String(text[range])
            guard !character.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
                return
            }

            do {
                guard let observation = try candidate.boundingBox(for: range) else {
                    failed = true
                    return
                }
                let box = observation.boundingBox
                guard box.width > 0, box.height > 0 else {
                    failed = true
                    return
                }
                characters.append(ScreenshotOCRCharacter(
                    range: range,
                    normalizedBounds: CGRect(
                        x: box.minX,
                        y: 1 - box.maxY,
                        width: box.width,
                        height: box.height
                    )
                ))
            } catch {
                failed = true
            }
        }

        return failed ? nil : characters
    }

    private static func appendVisualTextBlock(
        from text: String,
        range: Range<String.Index>,
        bounds: CGRect,
        confidence: Float,
        to blocks: inout [ScreenshotOCRBlock]
    ) {
        let segment = text[range].trimmingCharacters(in: .whitespacesAndNewlines)
        guard !segment.isEmpty else { return }
        blocks.append(ScreenshotOCRBlock(
            id: UUID(),
            text: segment,
            normalizedBounds: bounds,
            confidence: confidence
        ))
    }

    static func languageKey(for language: Locale.Language?) -> String {
        guard let language else { return "und" }
        let code = language.languageCode?.identifier.lowercased() ?? "und"
        if code == "zh" {
            return "zh-\(language.script?.identifier ?? "Hans")"
        }
        return code
    }

    private static func joinedText(_ left: String, _ right: String) -> String {
        let needsSpace = left.last?.isASCII == true || right.first?.isASCII == true
        return needsSpace ? "\(left) \(right)" : left + right
    }

    private static func ocrImage(from data: Data) -> CGImage? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil) else {
            return nil
        }
        return CGImageSourceCreateImageAtIndex(source, 0, [
            kCGImageSourceShouldCache: true
        ] as CFDictionary)
    }
}

extension ScreenshotTranslationService {
    func classify(
        _ blocks: [ScreenshotOCRBlock],
        targetLanguage: ScreenshotTranslationLanguage
    ) -> ScreenshotTranslationPlan {
        Self.classify(blocks, targetLanguage: targetLanguage)
    }

    static func classifyAsync(
        _ blocks: [ScreenshotOCRBlock],
        targetLanguage: ScreenshotTranslationLanguage
    ) async -> ScreenshotTranslationPlan {
        await Task.detached(priority: .userInitiated) {
            classify(blocks, targetLanguage: targetLanguage)
        }.value
    }
}
